version: '3'
services:
  rhel8:
    build:
      context: .docker/build
      dockerfile: Dockerfile_rhel8
    privileged: true
    command:
      - /sbin/init
    volumes:
      - "./rpmbuild/SPECS:/home/builder/rpmbuild/SPECS"
      - "./rpmbuild/SOURCES:/home/builder/rpmbuild/SOURCES"
      - "./docs/8:/home/builder/rpmbuild/RPMS"
      - "./docs/8/SRPMS:/home/builder/rpmbuild/SRPMS"
      - "./rpmbuild/build.bash:/home/builder/build.bash:ro"
      - "./specs:/home/builder/specs:ro"
      - "./sources:/home/builder/sources:ro"
    env_file:
      - "./.env"
  test-rhel8:
    build:
      context: .docker/test
      dockerfile: Dockerfile_rhel8
    privileged: true
    command:
      - /sbin/init
    volumes:
      - "./docs:/usr/local/repos"
  jekyll:
    build:
      context: .docker/jekyll
      dockerfile: Dockerfile
    volumes:
      - "./docs:/usr/src/app"
    command: jekyll serve -s /usr/src/app --watch --verbose --trace
    ports:
      - "${FORWARD_HOST:-0.0.0.0}:4000:4000"
