FROM almalinux:8
#COPY ../../docs /usr/local/repos

RUN yum update -y \
    && yum install -y epel-release libmaxminddb gd \
    && yum clean all

COPY nginx-mainline.repo /etc/yum.repos.d/nginx-mainline.repo
COPY docker-entry-point.sh /usr/local/bin/docker-entry-point.sh

RUN chown a+x /usr/local/bin/docker-entry-point.sh

EXPOSE 80
